# Generated by Django 6.0.1 on 2026-01-15 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=60, unique=True)),
                ('tara_origine', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('an_infiintare', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(default='Reducere', max_length=50)),
                ('procent', models.PositiveIntegerField()),
                ('data_start', models.DateField(blank=True, null=True)),
                ('data_sfarsit', models.DateField(blank=True, null=True)),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50, unique=True)),
                ('culoare_hex', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='DateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_user', models.CharField(blank=True, max_length=30, null=True)),
                ('vip', models.BooleanField(default=False)),
                ('a_cumparat', models.BooleanField(default=False)),
                ('data_inregistrarii', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('oferta', 'poate beneficia de reducere specială')],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=40, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronice.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('cod_produs', models.CharField(max_length=50, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stoc', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('disponibil', 'Disponibil'), ('indisponibil', 'Indisponibil'), ('precomanda', 'Precomanda')], default='disponibil', max_length=20)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronice.brand')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produse', to='electronice.categorie')),
                ('taguri', models.ManyToManyField(blank=True, related_name='produse', to='electronice.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Specificatie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume_atribut', models.CharField(max_length=100)),
                ('valoare', models.CharField(max_length=200)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificatii', to='electronice.produs')),
            ],
        ),
    ]
