# Generated by Django 6.0.1 on 2026-01-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='culoare',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='categorie',
            name='icon',
            field=models.CharField(default='●', max_length=50),
        ),
    ]
