# Generated by Django 6.0.1 on 2026-01-15 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronice', '0002_categorie_culoare_categorie_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dateclient',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dateclient',
            name='judet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dateclient',
            name='numar',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dateclient',
            name='strada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dateclient',
            name='tara',
            field=models.CharField(default='Romania', max_length=50),
        ),
        migrations.AddField(
            model_name='dateclient',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('display_user', models.CharField(blank=True, max_length=30, null=True)),
                ('vip', models.BooleanField(default=False)),
                ('a_cumparat', models.BooleanField(default=False)),
                ('data_inregistrarii', models.DateField(default=django.utils.timezone.now)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_users', to='electronice.produs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('oferta', 'poate beneficia de reducere specială')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_comanda', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'In asteptare'), ('processing', 'In procesare'), ('shipped', 'Expediat'), ('delivered', 'Livrat'), ('cancelled', 'Anulat')], default='pending', max_length=20)),
                ('total_pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresa_livrare', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_comanda'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField(default=1)),
                ('pret_unitar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='electronice.order')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronice.produs')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('data_review', models.DateTimeField(auto_now_add=True)),
                ('helpful_count', models.IntegerField(default=0)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='electronice.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_review'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Stea'), (2, '2 Stele'), (3, '3 Stele'), (4, '4 Stele'), (5, '5 Stele')])),
                ('data_rating', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='electronice.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_rating'],
                'unique_together': {('user', 'produs')},
            },
        ),
    ]
