# Generated by Django 6.0.1 on 2026-01-16 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronice', '0003_dateclient_cod_postal_dateclient_judet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='a_cumparat',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='data_inregistrarii',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='display_user',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='vip',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
