# Generated by Django 6.0.1 on 2026-01-16 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronice', '0004_remove_favorite_a_cumparat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-data_adaugare']},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'produs')},
        ),
    ]
