# Generated by Django 6.0.1 on 2026-01-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronice', '0005_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateclient',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dateclient',
            name='email_confirmat',
            field=models.BooleanField(default=False),
        ),
    ]
