# Generated by Django 6.0.1 on 2026-01-16 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronice', '0006_dateclient_cod_dateclient_email_confirmat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField()),
                ('descriere', models.TextField(blank=True, null=True)),
                ('procent_reducere', models.PositiveIntegerField(default=10)),
                ('activa', models.BooleanField(default=True)),
                ('categorii', models.ManyToManyField(related_name='promotii', to='electronice.categorie')),
            ],
            options={
                'ordering': ['-data_creare'],
            },
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizare', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizualizari', to='electronice.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizualizari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_vizualizare'],
            },
        ),
    ]
