# Generated by Django 6.0.1 on 2026-01-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronice', '0007_promotie_vizualizare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateclient',
            options={'permissions': [('vizualizeaza_oferta', 'Poate vizualiza oferta speciala cu reducere 50%')]},
        ),
    ]
